// Overwrites server/baked-secret.ts with the real ANCHOR_SYNC_SECRET so it
// ships into the compiled bundle for publish_website. Run BEFORE `npm run build`
// when preparing a published deployment. Do NOT commit the resulting file —
// it is gitignored.
//
// Usage:
//   ANCHOR_SYNC_SECRET=$(cat ../.secrets/anchor_sync_secret) tsx script/bake-secret.ts
//   npm run build
//
// To unbake (return to dev mode), restore the empty stub:
//   git checkout -- server/baked-secret.ts  (does nothing — file is gitignored)
//   echo 'export const BAKED_SYNC_SECRET = "";' > server/baked-secret.ts

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const secret = process.env.ANCHOR_SYNC_SECRET || "";
if (!secret) {
  console.error("[bake-secret] ANCHOR_SYNC_SECRET is not set; aborting");
  process.exit(1);
}

const target = resolve(__dirname, "..", "server", "baked-secret.ts");
const content = `// AUTO-GENERATED by script/bake-secret.ts — do not commit.
// This file ships in the publish_website tarball so the published sandbox
// has the orchestrator secret without needing runtime env injection.
export const BAKED_SYNC_SECRET = ${JSON.stringify(secret)};
`;
writeFileSync(target, content, "utf8");
console.log(`[bake-secret] wrote ${secret.length}-char secret to ${target}`);
